/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WaymakerApplyRouteImport } from './routes/waymaker.apply'
import { Route as WaymakerIdRouteImport } from './routes/waymaker.$id'
import { Route as WaitlistCodeRouteImport } from './routes/waitlist.$code'
import { Route as TripNewRouteImport } from './routes/trip.new'
import { Route as TripTokenRouteImport } from './routes/trip.$token'
import { Route as AdminPrelaunchAnalyticsRouteImport } from './routes/admin.prelaunch-analytics'
import { Route as TripConfirmationTokenRouteImport } from './routes/trip.confirmation.$token'
import { Route as TripTokenFeedbackRouteImport } from './routes/trip.$token.feedback'
import { Route as ApiPublicBootstrapAdminRouteImport } from './routes/api/public/bootstrap-admin'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WaymakerApplyRoute = WaymakerApplyRouteImport.update({
  id: '/waymaker/apply',
  path: '/waymaker/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const WaymakerIdRoute = WaymakerIdRouteImport.update({
  id: '/waymaker/$id',
  path: '/waymaker/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistCodeRoute = WaitlistCodeRouteImport.update({
  id: '/waitlist/$code',
  path: '/waitlist/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const TripNewRoute = TripNewRouteImport.update({
  id: '/trip/new',
  path: '/trip/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TripTokenRoute = TripTokenRouteImport.update({
  id: '/trip/$token',
  path: '/trip/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPrelaunchAnalyticsRoute = AdminPrelaunchAnalyticsRouteImport.update({
  id: '/prelaunch-analytics',
  path: '/prelaunch-analytics',
  getParentRoute: () => AdminRoute,
} as any)
const TripConfirmationTokenRoute = TripConfirmationTokenRouteImport.update({
  id: '/trip/confirmation/$token',
  path: '/trip/confirmation/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TripTokenFeedbackRoute = TripTokenFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => TripTokenRoute,
} as any)
const ApiPublicBootstrapAdminRoute = ApiPublicBootstrapAdminRouteImport.update({
  id: '/api/public/bootstrap-admin',
  path: '/api/public/bootstrap-admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/prelaunch-analytics': typeof AdminPrelaunchAnalyticsRoute
  '/trip/$token': typeof TripTokenRouteWithChildren
  '/trip/new': typeof TripNewRoute
  '/waitlist/$code': typeof WaitlistCodeRoute
  '/waymaker/$id': typeof WaymakerIdRoute
  '/waymaker/apply': typeof WaymakerApplyRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/trip/$token/feedback': typeof TripTokenFeedbackRoute
  '/trip/confirmation/$token': typeof TripConfirmationTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/prelaunch-analytics': typeof AdminPrelaunchAnalyticsRoute
  '/trip/$token': typeof TripTokenRouteWithChildren
  '/trip/new': typeof TripNewRoute
  '/waitlist/$code': typeof WaitlistCodeRoute
  '/waymaker/$id': typeof WaymakerIdRoute
  '/waymaker/apply': typeof WaymakerApplyRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/trip/$token/feedback': typeof TripTokenFeedbackRoute
  '/trip/confirmation/$token': typeof TripConfirmationTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/prelaunch-analytics': typeof AdminPrelaunchAnalyticsRoute
  '/trip/$token': typeof TripTokenRouteWithChildren
  '/trip/new': typeof TripNewRoute
  '/waitlist/$code': typeof WaitlistCodeRoute
  '/waymaker/$id': typeof WaymakerIdRoute
  '/waymaker/apply': typeof WaymakerApplyRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/trip/$token/feedback': typeof TripTokenFeedbackRoute
  '/trip/confirmation/$token': typeof TripConfirmationTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/sitemap.xml'
    | '/admin/prelaunch-analytics'
    | '/trip/$token'
    | '/trip/new'
    | '/waitlist/$code'
    | '/waymaker/$id'
    | '/waymaker/apply'
    | '/api/public/bootstrap-admin'
    | '/trip/$token/feedback'
    | '/trip/confirmation/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/sitemap.xml'
    | '/admin/prelaunch-analytics'
    | '/trip/$token'
    | '/trip/new'
    | '/waitlist/$code'
    | '/waymaker/$id'
    | '/waymaker/apply'
    | '/api/public/bootstrap-admin'
    | '/trip/$token/feedback'
    | '/trip/confirmation/$token'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/sitemap.xml'
    | '/admin/prelaunch-analytics'
    | '/trip/$token'
    | '/trip/new'
    | '/waitlist/$code'
    | '/waymaker/$id'
    | '/waymaker/apply'
    | '/api/public/bootstrap-admin'
    | '/trip/$token/feedback'
    | '/trip/confirmation/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TripTokenRoute: typeof TripTokenRouteWithChildren
  TripNewRoute: typeof TripNewRoute
  WaitlistCodeRoute: typeof WaitlistCodeRoute
  WaymakerIdRoute: typeof WaymakerIdRoute
  WaymakerApplyRoute: typeof WaymakerApplyRoute
  ApiPublicBootstrapAdminRoute: typeof ApiPublicBootstrapAdminRoute
  TripConfirmationTokenRoute: typeof TripConfirmationTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waymaker/apply': {
      id: '/waymaker/apply'
      path: '/waymaker/apply'
      fullPath: '/waymaker/apply'
      preLoaderRoute: typeof WaymakerApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waymaker/$id': {
      id: '/waymaker/$id'
      path: '/waymaker/$id'
      fullPath: '/waymaker/$id'
      preLoaderRoute: typeof WaymakerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist/$code': {
      id: '/waitlist/$code'
      path: '/waitlist/$code'
      fullPath: '/waitlist/$code'
      preLoaderRoute: typeof WaitlistCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/new': {
      id: '/trip/new'
      path: '/trip/new'
      fullPath: '/trip/new'
      preLoaderRoute: typeof TripNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/$token': {
      id: '/trip/$token'
      path: '/trip/$token'
      fullPath: '/trip/$token'
      preLoaderRoute: typeof TripTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/prelaunch-analytics': {
      id: '/admin/prelaunch-analytics'
      path: '/prelaunch-analytics'
      fullPath: '/admin/prelaunch-analytics'
      preLoaderRoute: typeof AdminPrelaunchAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/trip/confirmation/$token': {
      id: '/trip/confirmation/$token'
      path: '/trip/confirmation/$token'
      fullPath: '/trip/confirmation/$token'
      preLoaderRoute: typeof TripConfirmationTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/$token/feedback': {
      id: '/trip/$token/feedback'
      path: '/feedback'
      fullPath: '/trip/$token/feedback'
      preLoaderRoute: typeof TripTokenFeedbackRouteImport
      parentRoute: typeof TripTokenRoute
    }
    '/api/public/bootstrap-admin': {
      id: '/api/public/bootstrap-admin'
      path: '/api/public/bootstrap-admin'
      fullPath: '/api/public/bootstrap-admin'
      preLoaderRoute: typeof ApiPublicBootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminPrelaunchAnalyticsRoute: typeof AdminPrelaunchAnalyticsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPrelaunchAnalyticsRoute: AdminPrelaunchAnalyticsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface TripTokenRouteChildren {
  TripTokenFeedbackRoute: typeof TripTokenFeedbackRoute
}

const TripTokenRouteChildren: TripTokenRouteChildren = {
  TripTokenFeedbackRoute: TripTokenFeedbackRoute,
}

const TripTokenRouteWithChildren = TripTokenRoute._addFileChildren(
  TripTokenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TripTokenRoute: TripTokenRouteWithChildren,
  TripNewRoute: TripNewRoute,
  WaitlistCodeRoute: WaitlistCodeRoute,
  WaymakerIdRoute: WaymakerIdRoute,
  WaymakerApplyRoute: WaymakerApplyRoute,
  ApiPublicBootstrapAdminRoute: ApiPublicBootstrapAdminRoute,
  TripConfirmationTokenRoute: TripConfirmationTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
